---
kind: pipeline
type: exec
name: build

steps:
- name: build
  commands:
    - packer init .
    - packer build .
- name: push
  commands:
    - docker push registry.gatewayks.net/kester-cloud/puppet:latest