---
kind: pipeline
type: exec
name: build

steps:
  - name: build
    environment:
      SOPS_VERSION: "3.10.2"
      BOLT_VERSION: "4.0.0-1"
    commands:
      - make

  - name: push-remote
    environment:
      DOCKER_TOKEN:
        from_secret: DOCKER_TOKEN_AKESTER
    depends_on:
      - build
    commands:
      - make push-remote
    # when:
    #   branch:
    #     - master
