stages:
  - build
  - deploy

build-x86:
  stage: build
  tags:
    - exec
  script:
    - make build-x86
    - make push-x86

push-manifest:
  stage: deploy
  tags:
    - exec
  dependencies:
    - build-x86
  script:
    - make push-manifest
